version: "3"
services:
  file-server:
    build: .
    volumes:
      - ${IMAGES_DIRECTORY}:/home/files
    restart: always
    ports:
      - "${PORT}:${PORT}" 
    environment:
      DEBUG: project*
      #set base path. example /var/www/public/uploads/
      FILE_SERVER_BASE_PATH: ${IMAGES_DIRECTORY}
